---
# tasks file for delete-vpc-peering

- name: get vpc peering information
  ec2_vpc_peering_info:
    filters:
        "tag:Name": "my_vpc_peering"
        "status-code": "active"
  register: peering_connection

- name: save peering id
  set_fact:
    peering_id: "{{ peering_connection.result | map(attribute='vpc_peering_connection_id') | join(' ')}}"

- name: get default vpc info
  ec2_vpc_net_info:
    filters:
      "tag:Name": default
  register: default_vpc

- name: storing vpc ids
  set_fact:
    default_vpc_id: "{{ default_vpc.vpcs | map(attribute='vpc_id') | join(' ')}}"

- name: get route table
  ec2_vpc_route_table_info:
    filters:
      "tag:Name": "default-rt"
    region: "{{region}}"
  register: default_rt

- name: storing deafult route table id
  set_fact:
    rt_id: "{{ default_rt.route_tables | map(attribute='id') | join(' ')}}"

- name: delete routes
  ec2_vpc_route_table:
    vpc_id: "{{ default_vpc_id }}"
    route_table_id: "{{ rt_id }}"
    lookup: id
    state: absent

- name: Delete vpc peering peering connection
  ec2_vpc_peer:
    region: "{{ region }}"
    peering_id: "{{peering_id}}"
    state: absent
  register: vpc_peer_absent
  when: peering_id | length != 0
